name: "HTML Pipeline Report with Latest and History"

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Get interactive inputs
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          title: "Enter Report Parameters"
          interactive: |
            fields:
              - label: param1
                properties:
                  display: Parameter 1
                  type: text
                  required: true
              - label: param2
                properties:
                  display: Parameter 2
                  type: text
                  required: true
              - label: param3
                properties:
                  display: Parameter 3
                  type: text
                  required: true
              - label: param4
                properties:
                  display: Parameter 4
                  type: text
                  required: true
              - label: param5
                properties:
                  display: Parameter 5
                  type: text
                  required: true

      - name: Create report directories
        run: |
          mkdir -p reports
          mkdir -p history

      - name: Generate latest report
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          cat <<EOF > reports/latest.html
          <!DOCTYPE html>
          <html>
          <head>
              <title>Latest Report</title>
              <style>
                  body { font-family: Arial, sans-serif; margin: 20px; }
                  .parameter { margin: 10px 0; padding: 10px; background: #f5f5f5; }
              </style>
          </head>
          <body>
              <h1>Latest Report (Run #${{ github.run_number }})</h1>
              <p>Generated: $TIMESTAMP</p>
              <div class="parameter">Param1: ${{ steps.interactive-inputs.outputs.param1 }}</div>
              <div class="parameter">Param2: ${{ steps.interactive-inputs.outputs.param2 }}</div>
              <div class="parameter">Param3: ${{ steps.interactive-inputs.outputs.param3 }}</div>
              <div class="parameter">Param4: ${{ steps.interactive-inputs.outputs.param4 }}</div>
              <div class="parameter">Param5: ${{ steps.interactive-inputs.outputs.param5 }}</div>
              <p><a href="../history/index.html">View History</a></p>
          </body>
          </html>
          EOF

      - name: Add to history
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          cat <<EOF > history/${{ github.run_number }}.html
          <!DOCTYPE html>
          <html>
          <body>
              <h1>Run #${{ github.run_number }}</h1>
              <p>Param1: ${{ steps.interactive-inputs.outputs.param1 }}</p>
              <p>Param2: ${{ steps.interactive-inputs.outputs.param2 }}</p>
              <p>Param3: ${{ steps.interactive-inputs.outputs.param3 }}</p>
              <p>Param4: ${{ steps.interactive-inputs.outputs.param4 }}</p>
              <p>Param5: ${{ steps.interactive-inputs.outputs.param5 }}</p>
              <p><a href="../reports/latest.html">Back to Latest</a></p>
          </body>
          </html>
          EOF

          # Update history index
          {
            echo '<!DOCTYPE html><html><body><h1>Report History</h1><ul>'
            ls -v history/*.html | grep -v index.html | sort -Vr | while read file; do
              run_num=$(basename "$file" .html)
              echo "<li><a href=\"$run_num.html\">Run #$run_num</a></li>"
            done
            echo '</ul><p><a href="../reports/latest.html">Back to Latest</a></p></body></html>'
          } > history/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
          keep_files: true

      - name: Show URLs
        run: |
          echo "Latest Report URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports/latest.html"
          echo ""
          echo "History URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/index.html"
