name: "Push-Triggered HTML Pipeline Report with Stages"

on:
  push:
    branches:
      - main  # change if needed

permissions:
  contents: write

jobs:
  first-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Stage 1 - Echo message
        run: echo "Hello from Stage 1!"

  second-stage:
    runs-on: ubuntu-latest
    needs: first-stage
    outputs:
      param1: ${{ steps.interactive-inputs.outputs.param1 }}
      param2: ${{ steps.interactive-inputs.outputs.param2 }}
      param3: ${{ steps.interactive-inputs.outputs.param3 }}
      param4: ${{ steps.interactive-inputs.outputs.param4 }}
      param5: ${{ steps.interactive-inputs.outputs.param5 }}
    permissions:
      contents: write
    steps:
      - name: Stage 2 - Ask for parameters interactively
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          notifier-slack-enabled: "false"
          notifier-discord-enabled: "false"
          timeout: 300
          title: "Please provide 5 parameters"
          interactive: |
            fields:
              - label: param1
                properties:
                  display: Parameter 1
                  type: text
                  required: true
              - label: param2
                properties:
                  display: Parameter 2
                  type: text
                  required: true
              - label: param3
                properties:
                  display: Parameter 3
                  type: text
                  required: true
              - label: param4
                properties:
                  display: Parameter 4
                  type: text
                  required: true
              - label: param5
                properties:
                  display: Parameter 5
                  type: text
                  required: true

  third-stage:
    runs-on: ubuntu-latest
    needs: second-stage
    steps:
      - name: Stage 3 - Print parameters
        run: |
          echo "You entered:"
          echo "Parameter 1: ${{ needs.second-stage.outputs.param1 }}"
          echo "Parameter 2: ${{ needs.second-stage.outputs.param2 }}"
          echo "Parameter 3: ${{ needs.second-stage.outputs.param3 }}"
          echo "Parameter 4: ${{ needs.second-stage.outputs.param4 }}"
          echo "Parameter 5: ${{ needs.second-stage.outputs.param5 }}"

  publish-report:
    runs-on: ubuntu-latest
    needs: third-stage
    steps:
      - name: Checkout gh-pages branch
        run: |
          git clone --branch gh-pages \
            https://github.com/${{ github.repository }} public || mkdir -p public
          cd public
          git pull || true
          cd ..

      - name: Create HTML reports (latest + history)
        run: |
          mkdir -p public/history

          # Latest report
          cat <<EOF > public/index.html
          <html><head>
          <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
          <meta http-equiv="Pragma" content="no-cache" />
          <meta http-equiv="Expires" content="0" />
          </head><body>
          <h1>Pipeline Parameters Report (Latest)</h1>
          <p>Parameter 1: ${{ needs.second-stage.outputs.param1 }}</p>
          <p>Parameter 2: ${{ needs.second-stage.outputs.param2 }}</p>
          <p>Parameter 3: ${{ needs.second-stage.outputs.param3 }}</p>
          <p>Parameter 4: ${{ needs.second-stage.outputs.param4 }}</p>
          <p>Parameter 5: ${{ needs.second-stage.outputs.param5 }}</p>
          <p><a href="./history/${{ github.run_number }}.html">View this run's history</a></p>
          <p><a href="./history/index.html">View all history</a></p>
          </body></html>
          EOF

          # History entry
          cat <<EOF > public/history/${{ github.run_number }}.html
          <html><body>
          <h1>Pipeline Parameters Report (Run #${{ github.run_number }})</h1>
          <p>Parameter 1: ${{ needs.second-stage.outputs.param1 }}</p>
          <p>Parameter 2: ${{ needs.second-stage.outputs.param2 }}</p>
          <p>Parameter 3: ${{ needs.second-stage.outputs.param3 }}</p>
          <p>Parameter 4: ${{ needs.second-stage.outputs.param4 }}</p>
          <p>Parameter 5: ${{ needs.second-stage.outputs.param5 }}</p>
          <p><a href="../index.html">Back to latest</a></p>
          </body></html>
          EOF

          # Rebuild history index
          {
            echo "<html><body><h1>All History</h1><ul>"
            for file in $(ls public/history/*.html | sort -V); do
              fname=$(basename "$file")
              if [ "$fname" != "index.html" ]; then
                echo "<li><a href=\"$fname\">Run #${fname%.html}</a></li>"
              fi
            done
            echo "</ul><p><a href=\"../index.html\">Back to latest</a></p></body></html>"
          } > public/history/index.html

      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true

      - name: Show Report URLs
        run: |
          echo "Live report URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/?nocache=${{ github.run_id }}"
          echo "History for this run:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/${{ github.run_number }}.html"
          echo "History Index:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/"
