name: "Interactive Parameter Pipeline with HTML Publish"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-inputs:
    runs-on: ubuntu-latest
    outputs:
      param1: ${{ steps.interactive-inputs.outputs.param1 }}
      param2: ${{ steps.interactive-inputs.outputs.param2 }}
      param3: ${{ steps.interactive-inputs.outputs.param3 }}
      param4: ${{ steps.interactive-inputs.outputs.param4 }}
      param5: ${{ steps.interactive-inputs.outputs.param5 }}
    steps:
      - name: Ask for parameters interactively
        id: interactive-inputs
        uses: boasihq/interactive-inputs@v2
        with:
          ngrok-authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
          notifier-slack-enabled: "false"
          notifier-discord-enabled: "false"
          timeout: 300
          title: "Please provide 5 parameters"
          interactive: |
            fields:
              - label: param1
                properties:
                  display: Parameter 1
                  type: text
                  required: true
              - label: param2
                properties:
                  display: Parameter 2
                  type: text
                  required: true
              - label: param3
                properties:
                  display: Parameter 3
                  type: text
                  required: true
              - label: param4
                properties:
                  display: Parameter 4
                  type: text
                  required: true
              - label: param5
                properties:
                  display: Parameter 5
                  type: text
                  required: true

  publish-report:
    runs-on: ubuntu-latest
    needs: collect-inputs
    steps:
      - name: Download existing gh-pages branch
        run: |
          git clone --branch gh-pages \
            https://github.com/${{ github.repository }} public || mkdir -p public

      - name: Create HTML reports (latest + history)
        run: |
          mkdir -p public/history
          
          # Latest page
          cat <<EOF > public/index.html
          <html><body><h1>Pipeline Parameters Report (Latest)</h1>
          <p>Parameter 1: ${{ needs.collect-inputs.outputs.param1 }}</p>
          <p>Parameter 2: ${{ needs.collect-inputs.outputs.param2 }}</p>
          <p>Parameter 3: ${{ needs.collect-inputs.outputs.param3 }}</p>
          <p>Parameter 4: ${{ needs.collect-inputs.outputs.param4 }}</p>
          <p>Parameter 5: ${{ needs.collect-inputs.outputs.param5 }}</p>
          <p><a href="./history/${{ github.run_number }}.html">View history entry for this run</a></p>
          <p><a href="./history/index.html">View all history</a></p>
          </body></html>
          EOF

          # History entry
          cat <<EOF > public/history/${{ github.run_number }}.html
          <html><body><h1>Pipeline Parameters Report (Run #${{ github.run_number }})</h1>
          <p>Parameter 1: ${{ needs.collect-inputs.outputs.param1 }}</p>
          <p>Parameter 2: ${{ needs.collect-inputs.outputs.param2 }}</p>
          <p>Parameter 3: ${{ needs.collect-inputs.outputs.param3 }}</p>
          <p>Parameter 4: ${{ needs.collect-inputs.outputs.param4 }}</p>
          <p>Parameter 5: ${{ needs.collect-inputs.outputs.param5 }}</p>
          <p><a href="../index.html">Back to latest</a></p>
          </body></html>
          EOF

          # Rebuild history index
          {
            echo "<html><body><h1>All History</h1><ul>"
            for file in $(ls public/history/*.html | sort -V); do
              fname=$(basename "$file")
              if [ "$fname" != "index.html" ]; then
                echo "<li><a href=\"$fname\">Run #${fname%.html}</a></li>"
              fi
            done
            echo "</ul><p><a href=\"../index.html\">Back to latest</a></p></body></html>"
          } > public/history/index.html

      - name: Publish HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

      - name: Show Report URLs
        run: |
          echo "Live report URL (always latest):"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/?t=${{ github.run_id }}"
          echo "History URL for this run:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/${{ github.run_number }}.html"
          echo "History Index URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/history/"
